---
name: SWF-NeedsRecompile
version: 1.04
author:
  - 'Clotho Advanced Media, Inc. <cpan@clotho.com>'
abstract: Tests if any SWF or FLA file dependencies have changed
license: perl
requires:
  File::Slurp: 9999.09
  Regexp::Common: 2.12
build_requires:
  Test::More: 0
provides:
  SWF::NeedsRecompile:
    file: lib/SWF/NeedsRecompile.pm
    version: 1.04
generated_by: Module::Build version 0.2611
